/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-08-28

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <LampFunctions.h>
#include "stm32f0xx.h"

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

void delay(int count){
	int i;
	for (i=0;i<count;i++){

	}
}

char buffer[4] = ""; //instructions of length 4
int i = 0;

int main(void)
{

//	//Setup TIM3
//	//TIM3_CNT is timer 3 counter, holds counter val
//	//TIM3_PSC is prescaler
//	//TIM3_ARR is what timer counts to (period)
//	//TIM3_CCR1 is duty cycle
//	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; //Enable TIM3
//	TIM3->PSC = 1; //Set Prescaler to 1
//	TIM3->ARR = 3; //Set ARR (period) to 3*1/8M = 0.375us = 375ns
////	TIM3->CCMR2 |= TIM_CCMR2_OC1M_1 | TIM_CCMR2_OC1M_2; //set to PWM mode
//
//	//Setup TIM1
//	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN; //Enable TIM1
//	TIM1->PSC = 1; //Set Prescaler to 1
//	TIM1->ARR = 6; //Set ARR (period) to 6*1/8M = 0.750us = 750ns
//
//
	//void UART_TxChar(USART_TypeDef* USARTx, uint8_t ch);
	//void UART_TxString(USART_TypeDef* USARTx, uint8_t * str);

	NVIC_EnableIRQ(USART1_IRQn); //enable global interrupt for USART1
//	char* test = "hello";
	setupUART(USART1);
	setupI2C(I2C1);
//	I2CTransmitString(test, 5);

	/* Infinite loop */
	while (1)
	{
		if (i > 3){
			I2CTransmitString(buffer,4);
			i = 0;
		}
		delay(100);
		//UART_TxString(USART1, str);
//		UART_TxChar(USART1, (uint8_t)'A');
//		if ((USART1->ISR & USART_ISR_RXNE) == USART_ISR_RXNE) //if RX is not empty
//		  {
//		   char temp = USART1->RDR; //fetch the data received
//
//		   GPIOB->BSRR |= GPIO_BSRR_BS_14;
//		   delay(5000);
//		   GPIOB->BSRR |= GPIO_BSRR_BR_14;
//
//		   USART1->TDR = temp; //send back out
//		   while(!(USART1->ISR & USART_ISR_TC)); //wait for transmission to complete
//		  }

	}
}

//void UART_TxChar(USART_TypeDef* USARTx, uint8_t ch){
//	while(!(USARTx->ISR & USART_ISR_TXE)); //while transmit buffer not empty
//	USARTx->TDR = ch; //set char to be next thing transmitted
//	while(!(USARTx->ISR & USART_ISR_TC)); //wait for transmission to complete
//}
//
//void UART_TxString(USART_TypeDef* USARTx, uint8_t * str){
//	while(*str != 0){
//		UART_TxChar(USARTx, *str); //transmit char from string
//		str++; //to next char
//	}
//}

void USART1_IRQHandler(void){ //USART1 Interrupt Handler
	if((USART1->ISR & USART_ISR_RXNE) == USART_ISR_RXNE){ //if RX is not empty
		buffer[i] = (char)USART1->RDR; //clear buffer (and flag) by reading from it
		i = i + 1;
	}
//	else if ((USART1->ISR & USART_ISR_TXE) == USART_ISR_TC){ //if TX empty (just transmitted)
//		uint8_t temp = 0b11111111; //clear buffer (and flag) by reading from it
//		//return temp;
//	}
	//return 0;
}
